In [130]:
import pandas as pd

df_pt1 = pd.read_csv('df_final_web_data_pt_1.txt')
df_pt2 = pd.read_csv('df_final_web_data_pt_2.txt')
df_experi = pd.read_csv('df_final_experiment_clients.txt')
df_demo = pd.read_csv('df_final_demo.txt')
pd.set_option('display.max_rows',1000)

# combine original 3 data files: df_pt1 + df_pt2 + final_experiment 
df_12 = pd.concat([df_pt1,df_pt2],ignore_index=True)
df_merged_12_experi = pd.merge(df_12,df_experi, on='client_id',how='outer')

# totally remove 10764 useless duplicatd rows from above 
df_merged_unique = df_merged_12_experi.drop_duplicates(keep='first')
df_merged_unique_demo = pd.merge(df_merged_unique,df_demo, on='client_id',how='outer')
df_merged_4files = df_merged_unique_demo.drop_duplicates(keep='first')

# devide above last df into 2 group df( experient and non_experiment group)
df_expe     = df_merged_4files[df_merged_4files['Variation'].isna()]
df_non_expe = df_merged_4files[df_merged_4files['Variation'].notna()]

# clean non experient group df: remove all those rows(112 rows) which value are null for anyone of below column:
df_non_expe_cleaned = df_non_expe.dropna(subset=['clnt_tenure_yr','clnt_tenure_mnth','clnt_age','gendr','num_accts','bal','calls_6_mnth','logons_6_mnth'])

# clean experient group df
df_expe = df_expe[df_expe['gendr'] !='X']
df_expe.loc[df_expe['gendr']=='U','gendr']='Unknown'
df_expe.loc[df_expe['clnt_tenure_mnth']>12,'clnt_tenure_mnth']=df_expe['clnt_tenure_mnth'] % 12

#print(df_expe['clnt_tenure_mnth'].value_counts())
df_experiment.head(100)

,client_id,visitor_id,visit_id,process_step,date_time,Variation,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,169,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
1,169,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
2,169,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
3,169,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
4,169,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36,NaN,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0
5,336,64757908_3400128256,649044751_80905125055_554468,start,2017-06-01 07:42:43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,336,64757908_3400128256,649044751_80905125055_554468,start,2017-06-01 07:26:55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,546,475037402_89828530214,731811517_9330176838_94847,confirm,2017-06-17 10:05:42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,546,475037402_89828530214,731811517_9330176838_94847,step_3,2017-06-17 10:05:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,546,475037402_89828530214,731811517_9330176838_94847,step_2,2017-06-17 10:03:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,546,475037402_89828530214,731811517_9330176838_94847,step_1,2017-06-17 10:03:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,546,475037402_89828530214,731811517_9330176838_94847,start,2017-06-17 10:03:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,722,919259913_64837298108,984487154_55831795985_521110,confirm,2017-04-19 15:00:09,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
23,722,919259913_64837298108,984487154_55831795985_521110,step_3,2017-04-19 14:57:27,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
24,722,919259913_64837298108,984487154_55831795985_521110,step_2,2017-04-19 14:56:37,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
25,722,919259913_64837298108,984487154_55831795985_521110,step_1,2017-04-19 14:56:18,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
26,722,919259913_64837298108,984487154_55831795985_521110,start,2017-04-19 14:56:16,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
27,722,919259913_64837298108,984487154_55831795985_521110,step_1,2017-04-19 14:51:12,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
28,722,919259913_64837298108,984487154_55831795985_521110,step_2,2017-04-19 14:50:56,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
29,722,919259913_64837298108,984487154_55831795985_521110,step_1,2017-04-19 14:50:20,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
30,722,919259913_64837298108,984487154_55831795985_521110,start,2017-04-19 14:50:10,NaN,11.0,143.0,59.5,F,2.0,22466.17,1.0,1.0
31,786,439747392_30293505155,640294664_79662229470_499394,confirm,2017-06-01 11:05:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,786,439747392_30293505155,640294664_79662229470_499394,step_3,2017-06-01 11:04:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,786,439747392_30293505155,640294664_79662229470_499394,step_2,2017-06-01 11:03:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,786,439747392_30293505155,640294664_79662229470_499394,step_1,2017-06-01 11:01:26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,786,439747392_30293505155,640294664_79662229470_499394,start,2017-06-01 11:01:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,786,439747392_30293505155,640294664_79662229470_499394,start,2017-06-01 11:00:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,805,831412807_82548325803,905546080_75813398358_250101,step_1,2017-06-08 01:11:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,805,831412807_82548325803,905546080_75813398358_250101,start,2017-06-08 01:10:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,805,831412807_82548325803,451173196_11661340552_563345,start,2017-06-15 19:11:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,805,831412807_82548325803,451173196_11661340552_563345,step_2,2017-06-15 19:11:21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,805,831412807_82548325803,451173196_11661340552_563345,step_2,2017-06-15 19:09:26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,805,831412807_82548325803,451173196_11661340552_563345,step_1,2017-06-15 19:09:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,805,831412807_82548325803,451173196_11661340552_563345,start,2017-06-15 19:09:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,805,831412807_82548325803,72221519_52513154978_430287,step_1,2017-06-17 19:23:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,805,831412807_82548325803,72221519_52513154978_430287,start,2017-06-17 19:23:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,832,645971208_10952400740,704999523_65579948030_431837,confirm,2017-06-16 10:40:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,832,645971208_10952400740,704999523_65579948030_431837,step_3,2017-06-16 10:40:18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,832,645971208_10952400740,704999523_65579948030_431837,step_2,2017-06-16 10:39:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,832,645971208_10952400740,704999523_65579948030_431837,step_1,2017-06-16 10:39:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,832,645971208_10952400740,704999523_65579948030_431837,step_2,2017-06-16 10:39:19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,832,645971208_10952400740,704999523_65579948030_431837,step_1,2017-06-16 10:38:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,832,645971208_10952400740,704999523_65579948030_431837,start,2017-06-16 10:38:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,1039,637213403_33482244512,621771101_68048173682_933803,confirm,2017-06-02 01:03:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,1039,637213403_33482244512,621771101_68048173682_933803,step_3,2017-06-02 01:02:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,1039,637213403_33482244512,621771101_68048173682_933803,step_2,2017-06-02 01:01:02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,1039,637213403_33482244512,621771101_68048173682_933803,step_1,2017-06-02 01:00:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,1039,637213403_33482244512,621771101_68048173682_933803,start,2017-06-02 01:00:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,1281,413028693_54657981595,7998667_91374757247_847638,confirm,2017-05-23 20:06:52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,1281,413028693_54657981595,7998667_91374757247_847638,step_3,2017-05-23 20:05:36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,1281,413028693_54657981595,7998667_91374757247_847638,step_2,2017-05-23 20:03:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,1281,413028693_54657981595,7998667_91374757247_847638,step_1,2017-05-23 20:02:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,1281,413028693_54657981595,7998667_91374757247_847638,step_1,2017-05-23 20:01:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,1281,413028693_54657981595,7998667_91374757247_847638,start,2017-05-23 20:01:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,1357,653660855_41663230035,874150516_64146600964_876576,confirm,2017-05-24 14:01:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,1357,653660855_41663230035,874150516_64146600964_876576,step_3,2017-05-24 13:59:59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,1357,653660855_41663230035,874150516_64146600964_876576,step_2,2017-05-24 13:58:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,1357,653660855_41663230035,874150516_64146600964_876576,step_1,2017-05-24 13:57:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,1357,653660855_41663230035,874150516_64146600964_876576,start,2017-05-24 13:57:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,1399,395313004_27952045034,355891466_83298426087_683392,confirm,2017-05-10 11:03:03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,1399,395313004_27952045034,355891466_83298426087_683392,step_3,2017-05-10 11:02:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,1399,395313004_27952045034,355891466_83298426087_683392,step_2,2017-05-10 11:01:37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,1399,395313004_27952045034,355891466_83298426087_683392,step_1,2017-05-10 11:01:25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,1399,395313004_27952045034,355891466_83298426087_683392,start,2017-05-10 11:01:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,1399,395313004_27952045034,355891466_83298426087_683392,step_1,2017-05-10 10:59:15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,1399,395313004_27952045034,355891466_83298426087_683392,start,2017-05-10 10:59:11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,1508,685797332_19561245748,673746462_59870037712_480649,confirm,2017-06-01 13:17:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,1508,685797332_19561245748,673746462_59870037712_480649,confirm,2017-06-01 13:01:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,1508,685797332_19561245748,673746462_59870037712_480649,confirm,2017-06-01 12:45:18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,1508,685797332_19561245748,673746462_59870037712_480649,confirm,2017-06-01 12:29:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,1508,685797332_19561245748,673746462_59870037712_480649,confirm,2017-06-01 12:13:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,1508,685797332_19561245748,673746462_59870037712_480649,step_3,2017-06-01 12:12:41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,1508,685797332_19561245748,673746462_59870037712_480649,step_2,2017-06-01 12:12:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,1508,685797332_19561245748,673746462_59870037712_480649,step_1,2017-06-01 12:11:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,1508,685797332_19561245748,673746462_59870037712_480649,start,2017-06-01 12:11:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:32:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,1531,934069404_34543643308,110350144_67985219545_904677,confirm,2017-06-02 22:25:26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,1531,934069404_34543643308,110350144_67985219545_904677,step_3,2017-06-02 22:25:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,1531,934069404_34543643308,110350144_67985219545_904677,step_2,2017-06-02 22:23:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,1531,934069404_34543643308,110350144_67985219545_904677,step_1,2017-06-02 22:22:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,1531,934069404_34543643308,110350144_67985219545_904677,start,2017-06-02 22:22:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,1543,498785241_50825025698,48544987_94878616044_157787,confirm,2017-04-05 15:13:54,NaN,11.0,139.0,51.5,M,4.0,569096.60,3.0,3.0
158,1543,498785241_50825025698,48544987_94878616044_157787,step_3,2017-04-05 15:12:46,NaN,11.0,139.0,51.5,M,4.0,569096.60,3.0,3.0
159,1543,498785241_50825025698,48544987_94878616044_157787,step_2,2017-04-05 15:10:51,NaN,11.0,139.0,51.5,M,4.0,569096.60,3.0,3.0
160,1543,498785241_50825025698,48544987_94878616044_157787,step_1,2017-04-05 15:10:26,NaN,11.0,139.0,51.5,M,4.0,569096.60,3.0,3.0
161,1543,498785241_50825025698,48544987_94878616044_157787,start,2017-04-05 15:10:20,NaN,11.0,139.0,51.5,M,4.0,569096.60,3.0,3.0
162,1543,498785241_50825025698,48544987_94878616044_157787,start,2017-04-05 15:09:16,NaN,11.0,139.0,51.5,M,4.0,569096.60,3.0,3.0
163,1621,45031672_9874942918,178305257_74757299896_508747,confirm,2017-06-06 15:44:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,1621,45031672_9874942918,178305257_74757299896_508747,step_3,2017-06-06 15:42:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,1621,45031672_9874942918,178305257_74757299896_508747,step_2,2017-06-06 15:40:18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,1621,45031672_9874942918,178305257_74757299896_508747,step_1,2017-06-06 15:39:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,1621,45031672_9874942918,178305257_74757299896_508747,start,2017-06-06 15:37:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,1621,45031672_9874942918,771435490_64870878862_124506,start,2017-06-02 18:49:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,1621,45031672_9874942918,771435490_64870878862_124506,start,2017-06-02 18:47:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,1677,361240963_15830034505,494607202_74539107264_966618,start,2017-03-31 11:01:50,NaN,23.0,280.0,43.0,M,2.0,152953.71,7.0,7.0
181,1677,361240963_15830034505,494607202_74539107264_966618,step_2,2017-03-31 11:00:40,NaN,23.0,280.0,43.0,M,2.0,152953.71,7.0,7.0
182,1677,361240963_15830034505,494607202_74539107264_966618,step_1,2017-03-31 10:59:41,NaN,23.0,280.0,43.0,M,2.0,152953.71,7.0,7.0
183,1677,361240963_15830034505,494607202_74539107264_966618,start,2017-03-31 10:59:27,NaN,23.0,280.0,43.0,M,2.0,152953.71,7.0,7.0
184,1677,361240963_15830034505,629581112_28553609634_798207,confirm,2017-05-04 11:43:19,NaN,23.0,280.0,43.0,M,2.0,152953.71,7.0,7.0